"""Indexed url column and id column for users

Revision ID: 0b9a29d56041
Revises: c7a9d92ee15a
Create Date: 2025-01-29 15:12:01.390189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b9a29d56041'
down_revision: Union[str, None] = 'c7a9d92ee15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_url_key', 'articles', type_='unique')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_preferences', 'saved_articles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_preferences', 'preferred_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_preferences', 'preferred_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('user_preferences', 'preferred_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_preferences', 'preferred_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_preferences', 'saved_articles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_unique_constraint('articles_url_key', 'articles', ['url'])
    # ### end Alembic commands ###
