"""add_soft_delete_to_articles_and_users

Revision ID: cd8588c2f6aa
Revises: e24843e01b7c
Create Date: 2025-02-15 18:36:33.404834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8588c2f6aa'
down_revision: Union[str, None] = 'e24843e01b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    op.add_column('articles', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'is_deleted')
    # ### end Alembic commands ###
